### ISSUE TITLE
Parameterize target folder

### ISSUE THREAD

**Issue by dustine32** [USCbiostats/peregrine#1]
Currently, the `steps.sh` pipeline code is strict about creating folders that already exist and fails when rerunning. This would be manageable if the produced folders (and files) were not created under folders currently tracked by git (e.g., `eQTL`, `heirarchicalTAD`) because then I could just delete the whole folder and restart rather than removing the folders and files individually.

It would be nice to direct all new file creation to a folder that's not git-tracked. This change would make it easier to run the pipeline repeatedly by deleting the folder or specifying a different folder name. I typically will just call this folder "target" and maybe append the ISO-formatted date like "target_20240319". But this folder name should be up to the person running it by making it a parameter, like:
```
./steps.sh target_20240319
```
This would create a new folder `target_20240319` in the current working directory. So if at the root `peregrine` path, this would result in:
```
peregrine/
   target_20240319/
      eQTL_files_and_whatnot/
         Minor_Salivary_Gland/
            ...
```
Not sure about the exact required folder structure but if I didn't like something about the produced files I could just make a fix, delete `target_20240319`, and then rerun.

I have a decent start on branch https://github.com/dustine32/peregrine/tree/target-path-refactor but it's definitely not finished.

**Comment by akshala** [comment]
Solved by Pull request #2
