### ISSUE TITLE
Commented-out idmapping_processing step breaks code

### ISSUE THREAD

**Issue by dustine32** [USCbiostats/peregrine#4]
When running `./steps.sh target` I get this `FileNotFoundError`:
```
eQTL done
Traceback (most recent call last):
  File "/project/huaiyumi_14/hm/debert/peregrine/heirarchicalTAD/heirarchicalTAD.py", line 197, in <module>
    HGNC2PANTH(os.path.join(folder, 'nn_' + file_name + '_intersect'), os.path.join(folder, file_name + '_out'), id_output_file, os.path.join(folder, 'unmatched'), tissue)
  File "/project/huaiyumi_14/hm/debert/peregrine/heirarchicalTAD/heirarchicalTAD.py", line 58, in HGNC2PANTH
    HGNC_mapping = open(hgnc_file, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'target/heirarchicalTAD/resultsHGNC.txt'
```
It looks like this missing `resultsHGNC.txt` file wasn't created because this line was commented out:
https://github.com/USCbiostats/peregrine/blob/91ec59f18dc323a79e2840f4e6ed2269d774088a/heirarchicalTAD/heirarchicalTAD.py#L174

Simply, uncommenting it back in seems to fix the whole pipeline so I'll make a PR for this change. @akshala Unless this is meant to be commented out?

**Comment by akshala** [comment]
I had done that while making the folder refactor code changes because I didn't want this to run again. It needs to be uncommented. Thanks for making this change!
